# Generated by Django 4.0.1 on 2022-02-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpost',
            name='upload',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
