# Generated by Django 4.0.1 on 2022-02-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0004_categorydata'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='categorydata',
            constraint=models.UniqueConstraint(fields=('post', 'categoryName'), name='unique_category'),
        ),
    ]
