# Generated by Django 4.0.1 on 2022-02-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0006_remove_categorydata_unique_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
